version: "3.8"
services:
 client:
   build:
     context: .
     dockerfile: Dockerfile
   environment:
     REACT_APP_API_URL: 192.168.1.30
   ports:
     - "3300:3000"
   volumes:
     - "./:/app"
     - "./:/node_modules"
   image: fatca:react
   container_name: react_container
   command: npm start  
     